name: Test Coverage
on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: [8.2]
        laravel: [11.*]
        dependency-version: [prefer-stable]

    env:
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      DB_CONNECTION: testing
      APP_KEY: base64:2fl+Ktvkfl+Fuz3Qp/A76G2RTiGVA/ZjKZaz6fiiM10=
      APP_ENV: testing
      BCRYPT_ROUNDS: 10
      MAIL_MAILER: array
      TELESCOPE_ENABLED: false

    # Docs: https://docs.github.com/en/actions/using-containerized-services
    services:
      elasticsearch:
        image: elasticsearch:7.17.3
        env:
          discovery.type: single-node
          ES_JAVA_OPTS: '-Xms512m -Xmx512m'
        ports:
          - 9200:9200
        options: --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=5

      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    name: Coverage P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v4

      - name: Verify Elasticsearch connection ðŸ§©
        run: |
          curl -X GET "localhost:${{ job.services.elasticsearch.ports['9200'] }}/_cluster/health?pretty=true"

      - name: Setup PHP ðŸ—
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: xdebug
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, mysql

      - name: Require Laravel Version âœˆ
        run: >
          composer require
          "illuminate/support:${{ matrix.laravel }}"
          "illuminate/container:${{ matrix.laravel }}"
          "illuminate/database:${{ matrix.laravel }}"
          "illuminate/events:${{ matrix.laravel }}"
          --no-interaction --no-update

      - name: Install Composer dependencies ðŸ’»
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist --optimize-autoloader

      - name: List Installed Dependencies ðŸ“¦
        run: composer show -D

      # Code quality

      - name: Run tests with coverage ðŸ§ª
        run: |
          ./vendor/bin/pest  --version
          ./vendor/bin/pest --coverage-clover clover.xml
        env:
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
          ELASTICSEARCH_PORT: ${{ job.services.elasticsearch.ports['9200'] }}

      - name: Generate test coverage badge ðŸ–¼
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          coverage_badge_path: 'badge-coverage.svg'
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
